# docker-compose.gpu.yml
version: '3.8'

services:
  ollama:
    # Wstrzyknięcie obsługi karty L4 do istniejącego kontenera
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]